package_name: chasca
genshin_id: 10000104
key: chasca
action_param_keys:
  attack:
    - param: "travel"
  aim:
    - param: "hold"
    - param: "travel"
    - param: "weakspot"
icd_tags:
  - ICDTagChascaShot
  - ICDTagChascaBurst
icd_groups:
  - group_name: ICDGroupChascaShot
    reset_timer: 90
    ele_app_sequence: [1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  - group_name: ICDGroupChascaBurst
    ele_app_sequence: [1, 0, 1, 0, 1, 0]
    damage_sequence: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
skill_data_mapping:
  attack:
    aim:
      - 8 # Aimed Shot|{param8:F1P}
    attack_1:
      - 0 # 1-Hit DMG|{param0:F1P}
    attack_2:
      - 1 # 2-Hit DMG|{param1:F1P}
    attack_3:
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
      - 2 # 3-Hit DMG|{param2:F1P}+{param3:F1P}
    attack_4:
      - 4 # 4-Hit DMG|{param4:F1P}
    ca:
      - 5 # Charged Attack DMG|{param4:F1P}
  skill:
    skillDMG:
      - 0 # Skill DMG|{param0:P}
    skillMultitarget:
      - 1
    skillShadowhunt:
      - 2
    skillShiningShadowhunt:
      - 3
  burst:
    burstDMG:
      - 0 # Skill DMG|{param0:F1P}
    burstSoulseeker:
      - 1
    burstRadiantSoulseeker:
      - 2
