package_name: ororon
genshin_id: 10000105
key: ororon
action_param_keys:
    attack:
        - param: "travel"
    aim:
        - param: "hold"
        - param: "travel"
        - param: "weakspot"
    skill:
        - param: "travel"
skill_data_mapping:
    attack: # Normal Attack: Spiritvessel Snapshot
        attack_1:
            - 0 # 1-Hit DMG|{param0:F1P}
        attack_2:
            - 1 # 2-Hit DMG|{param1:F1P}
        attack_3:
            - 2 # 3-Hit DMG|{param2:F1P}
        aim:
            - 3 # Aimed Shot|{param3:F1P}
        fullaim:
            - 4 # Fully-Charged Aimed Shot|{param4:P}
    skill: # Night's Sling
        skill:
            - 0 # Spirit Orb DMG|{param0:F1P}
    burst: # Dark Voices Echo
        burstRitual:
            - 0 # Ritual DMG|{param0:F1P}
        burstSonic:
            - 1 # Soundwave Collision DMG|{param1:F1P}
